#!/usr/bin/env bash

conda update -n base -c defaults conda
pip install tensorflow==2.9
pip install gdown
pip install opencv-python
pip install scipy
conda install -c conda-forge matplotlib
conda install -c conda-forge jupyterlab

set -e